{% set name = "NumCpp" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dpilger26/{{ name }}/archive/refs/tags/Version_{{ version }}.tar.gz
  sha256: f7d3a11d12f3209c95c098d0566e6aee072cfc493f1e9376796c91520958686f

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - cmake >=3.14
  host:
    - boost-cpp
  run:
    - bzip2
    - zlib

test:
  commands:
    - test -f $PREFIX/include/NumCpp.hpp
    - test -f $PREFIX/include/NumCpp/NdArray.hpp
    - test -f $PREFIX/share/NumCpp/cmake/NumCppConfig.cmake

about:
  home: https://github.com/dpilger26/NumCpp
  summary: 'A Templatized Header Only C++ Implementation of the Python NumPy Library'
  description: |
    A Templatized Header Only C++ Implementation of the Python NumPy Library for numerical computing.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://dpilger26.github.io/NumCpp/doxygen/html/index.html
  dev_url: https://github.com/dpilger26/NumCpp

extra:
  recipe-maintainers:
    - notestaff
